name: Build
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "gradle"
      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Compile javascript
        run: ./gradlew generateJavaScript
      - name: Compile web assets
        run: bash ./CompileEPK.sh
      - name: Upload web files
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: |
            javascript/lang/
            javascript/index.html
            javascript/classes.js
            javascript/classes.js.map
            javascript/favicon.ico
            javascript/assets.epk
      - name: Copy web files to _site/
        if: github.ref == 'refs/heads/main'
        run: mkdir _site/ && cp --recursive --target-directory=_site/
          javascript/lang/
          javascript/index.html
          javascript/classes.js
          javascript/classes.js.map
          javascript/favicon.ico
          javascript/assets.epk
      - name: Upload github-pages artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
      - name: Remove game music for offline version
        run: rm --recursive desktopRuntime/resources/assets/minecraft/sounds/music/game
      - name: Compile offline assets
        run: bash CompileEPK.sh
      - name: Make offline download
        run: bash MakeOfflineDownload.sh
      - name: Upload offline download
        uses: actions/upload-artifact@v4
        with:
          name: offline
          path: javascript/Shadow_Client_Offline.html

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: "pages"
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to github pages
        uses: actions/deploy-pages@v4
      - name: Delete github-pages artifact
        uses: GeekyEggo/delete-artifact@v5
        with:
          name: github-pages
