name: build and deploy
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: setup java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'
    - name: validate gradle wrapper
      uses: gradle/actions/wrapper-validation@v3
    - name: compile javascript
      run: chmod +x ./gradlew && ./gradlew generateJavascript --no-daemon
    - name: compile assets
      run: bash CompileEPK.sh
    - name: make offline download
      run: bash MakeOfflineDownload.sh
    - name: upload web version 
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: |
          javascript/lang
          javascript/index.html
          javascript/classes.js
          javascript/classes.js.map
          javascript/assets.epk
    - name: upload offline
      uses: actions/upload-artifact@v4
      with:
        name: offline
        path: javascript/Shadow_Client_Offline.html
    - name: copy web files to _site/
      if: github.ref == 'refs/heads/main'
      run: mkdir _site/ && cp --recursive --target-directory=_site/
        javascript/lang/
        javascript/index.html
        javascript/classes.js
        javascript/classes.js.map
        javascript/assets.epk
    - name: upload github-pages artifact
      if: github.ref == 'refs/heads/main'
      uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    concurrency:
      group: "pages"
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      uses: actions/deploy-pages@v4
    - name: delete github-pages artifact
      uses: GeekyEggo/delete-artifact@v5
      with:
        name: github-pages
