name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: setup gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
        cache-disabled: true
    - name: compile javascript
      run: bash CompileJS.sh
    - name: make offline download
      run: bash MakeOfflineDownload.sh
    - name: upload web version 
      uses: actions/upload-artifact@v4
      with:
        name: web
        path: |
          javascript/index.html
          javascript/classes.js
          javascript/classes.js.map
          javascript/favicon.png
    - name: upload offline
      uses: actions/upload-artifact@v4
      with:
        name: offline
        path: javascript/Shadow_Client_Offline.html
